const doctorData = [
    {
      name: "Dr. John Smith",
      age: 45,
      dob: "1979-04-12",
      gender: "male",
      email: "john.smith@example.com",
      password: "docpassword123",
      specialization: "Cardiology",
      phone: "+1 555-123-4567",
      role: "doctor",
      experience: ["Cardiac Surgery", "Echocardiography"],
      appointments: [],
      qualifications: ["MBBS", "MD (Cardiology)"],
      department: "Cardiology"
    },
    {
      name: "Dr. Jane Doe",
      age: 38,
      dob: "1986-07-20",
      gender: "female",
      email: "jane.doe@example.com",
      password: "docpassword123",
      specialization: "Pediatrics",
      phone: "+1 555-234-5678",
      role: "doctor",
      experience: ["Child Health", "Vaccinations"],
      appointments: [],
      qualifications: ["MBBS", "DCH"],
      department: "Pediatrics"
    },
    {
      name: "Dr. Michael Johnson",
      age: 50,
      dob: "1974-01-15",
      gender: "male",
      email: "michael.johnson@example.com",
      password: "docpassword123",
      specialization: "Orthopedics",
      phone: "+1 555-345-6789",
      role: "doctor",
      experience: ["Joint Replacement", "Sports Injuries"],
      appointments: [],
      qualifications: ["MBBS", "MS (Orthopedics)"],
      department: "Orthopedics"
    },
    {
      name: "Dr. Emily Davis",
      age: 42,
      dob: "1982-03-10",
      gender: "female",
      email: "emily.davis@example.com",
      password: "docpassword123",
      specialization: "Dermatology",
      phone: "+1 555-456-7890",
      role: "doctor",
      experience: ["Cosmetic Dermatology", "Skin Cancer"],
      appointments: [],
      qualifications: ["MBBS", "MD (Dermatology)"],
      department: "Dermatology"
    },
    {
      name: "Dr. Robert Brown",
      age: 55,
      dob: "1969-08-22",
      gender: "male",
      email: "robert.brown@example.com",
      password: "docpassword123",
      specialization: "Neurology",
      phone: "+1 555-567-8901",
      role: "doctor",
      experience: ["Stroke Management", "Epilepsy Treatment"],
      appointments: [],
      qualifications: ["MBBS", "DM (Neurology)"],
      department: "Neurology"
    },
    {
      name: "Dr. Sarah Wilson",
      age: 35,
      dob: "1989-12-05",
      gender: "female",
      email: "sarah.wilson@example.com",
      password: "docpassword123",
      specialization: "Psychiatry",
      phone: "+1 555-678-9012",
      role: "doctor",
      experience: ["Anxiety Disorders", "Behavioral Therapy"],
      appointments: [],
      qualifications: ["MBBS", "MD (Psychiatry)"],
      department: "Psychiatry"
    },
    {
      name: "Dr. Richard Taylor",
      age: 48,
      dob: "1976-09-30",
      gender: "male",
      email: "richard.taylor@example.com",
      password: "docpassword123",
      specialization: "Endocrinology",
      phone: "+1 555-789-0123",
      role: "doctor",
      experience: ["Diabetes Management", "Thyroid Disorders"],
      appointments: [],
      qualifications: ["MBBS", "DM (Endocrinology)"],
      department: "Endocrinology"
    },
    {
      name: "Dr. Laura Moore",
      age: 40,
      dob: "1984-11-18",
      gender: "female",
      email: "laura.moore@example.com",
      password: "docpassword123",
      specialization: "Oncology",
      phone: "+1 555-890-1234",
      role: "doctor",
      experience: ["Chemotherapy", "Radiation Therapy"],
      appointments: [],
      qualifications: ["MBBS", "DM (Oncology)"],
      department: "Oncology"
    },
    {
      name: "Dr. David Clark",
      age: 52,
      dob: "1972-02-14",
      gender: "male",
      email: "david.clark@example.com",
      password: "docpassword123",
      specialization: "Gastroenterology",
      phone: "+1 555-901-2345",
      role: "doctor",
      experience: ["Endoscopy", "Liver Diseases"],
      appointments: [],
      qualifications: ["MBBS", "DM (Gastroenterology)"],
      department: "Gastroenterology"
    },
    {
      name: "Dr. Olivia Anderson",
      age: 33,
      dob: "1991-06-25",
      gender: "female",
      email: "olivia.anderson@example.com",
      password: "docpassword123",
      specialization: "Pulmonology",
      phone: "+1 555-012-3456",
      role: "doctor",
      experience: ["Asthma Management", "Lung Infections"],
      appointments: [],
      qualifications: ["MBBS", "MD (Pulmonology)"],
      department: "Pulmonology"
    }
  ];
  
  export default doctorData;
  