const labTechData = [
    {
      name: "Alice Johnson",
      age: 30,
      dob: "1994-02-28",
      gender: "female",
      email: "alice.johnson@example.com",
      password: "labtechpassword123",
      phone: "+1 555-123-4567",
      role: "labtech",
      experience: 5,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Blood Test", "Urine Test"],
      specializedIn: ["Blood Tests", "Urine Tests"]
    },
    {
      name: "Bob Smith",
      age: 35,
      dob: "1989-06-15",
      gender: "male",
      email: "bob.smith@example.com",
      password: "labtechpassword123",
      phone: "+1 555-234-5678",
      role: "labtech",
      experience: 7,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Blood Test", "PCR Test"],
      specializedIn: ["Blood Tests", "PCR Tests"]
    },
    {
      name: "Catherine Lee",
      age: 28,
      dob: "1996-03-22",
      gender: "female",
      email: "catherine.lee@example.com",
      password: "labtechpassword123",
      phone: "+1 555-345-6789",
      role: "labtech",
      experience: 4,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Urine Test", "Biopsy"],
      specializedIn: ["Urine Tests", "Biopsy"]
    },
    {
      name: "David Brown",
      age: 40,
      dob: "1984-11-30",
      gender: "male",
      email: "david.brown@example.com",
      password: "labtechpassword123",
      phone: "+1 555-456-7890",
      role: "labtech",
      experience: 10,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Blood Test", "Urine Test", "COVID Test"],
      specializedIn: ["Blood Tests", "COVID Tests"]
    },
    {
      name: "Eva Green",
      age: 32,
      dob: "1992-09-10",
      gender: "female",
      email: "eva.green@example.com",
      password: "labtechpassword123",
      phone: "+1 555-567-8901",
      role: "labtech",
      experience: 6,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Blood Test", "X-ray"],
      specializedIn: ["Blood Tests", "X-ray"]
    },
    {
      name: "Frank White",
      age: 38,
      dob: "1986-04-25",
      gender: "male",
      email: "frank.white@example.com",
      password: "labtechpassword123",
      phone: "+1 555-678-9012",
      role: "labtech",
      experience: 8,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Blood Test", "Urine Test"],
      specializedIn: ["Blood Tests", "Urine Tests"]
    },
    {
      name: "Grace Martin",
      age: 29,
      dob: "1995-12-12",
      gender: "female",
      email: "grace.martin@example.com",
      password: "labtechpassword123",
      phone: "+1 555-789-0123",
      role: "labtech",
      experience: 5,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Urine Test", "Blood Test"],
      specializedIn: ["Urine Tests", "Blood Tests"]
    },
    {
      name: "Harry Scott",
      age: 34,
      dob: "1990-07-19",
      gender: "male",
      email: "harry.scott@example.com",
      password: "labtechpassword123",
      phone: "+1 555-890-1234",
      role: "labtech",
      experience: 9,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Blood Test", "Urine Test", "HIV Test"],
      specializedIn: ["Blood Tests", "HIV Tests"]
    },
    {
      name: "Ivy Walker",
      age: 27,
      dob: "1997-01-05",
      gender: "female",
      email: "ivy.walker@example.com",
      password: "labtechpassword123",
      phone: "+1 555-901-2345",
      role: "labtech",
      experience: 3,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Blood Test", "Saliva Test"],
      specializedIn: ["Blood Tests", "Saliva Tests"]
    },
    {
      name: "Jack Thomas",
      age: 45,
      dob: "1979-10-20",
      gender: "male",
      email: "jack.thomas@example.com",
      password: "labtechpassword123",
      phone: "+1 555-012-3456",
      role: "labtech",
      experience: 12,
      qualification: "B.Sc in Medical Laboratory Technology",
      testConducted: ["Blood Test", "Urine Test", "CT Scan"],
      specializedIn: ["Blood Tests", "CT Scans"]
    }
  ];
  
  export default labTechData;
  