const patientData = [
    {
      name: "John Doe",
      age: 35,
      dob: "1989-05-14",
      gender: "male",
      email: "john.doe@example.com",
      password: "patientpassword123",
      phone: "+1 555-111-2233",
      role: "patient",
      bloodType: "O+",
      medicalHistory: ["Hypertension", "Asthma"],
      allergies: ["Peanuts", "Dust"],
      currentMedication: ["Atenolol", "Albuterol"],
      testTaken: ["Blood Test", "Chest X-ray"],
      appointments: [],
      reports: [],
    },
    {
      name: "Jane Smith",
      age: 42,
      dob: "1982-11-30",
      gender: "female",
      email: "jane.smith@example.com",
      password: "patientpassword123",
      phone: "+1 555-222-3344",
      role: "patient",
      bloodType: "A-",
      medicalHistory: ["Diabetes", "Cholesterol"],
      allergies: ["Penicillin"],
      currentMedication: ["Metformin", "Simvastatin"],
      testTaken: ["Blood Test", "ECG"],
      appointments: [],
      reports: [],
    },
    {
      name: "Emily Johnson",
      age: 28,
      dob: "1996-03-22",
      gender: "female",
      email: "emily.johnson@example.com",
      password: "patientpassword123",
      phone: "+1 555-333-4455",
      role: "patient",
      bloodType: "B+",
      medicalHistory: ["Migraines"],
      allergies: ["Latex"],
      currentMedication: ["Sumatriptan"],
      testTaken: ["Blood Test"],
      appointments: [],
      reports: [],
    },
    {
      name: "Michael Lee",
      age: 50,
      dob: "1974-02-14",
      gender: "male",
      email: "michael.lee@example.com",
      password: "patientpassword123",
      phone: "+1 555-444-5566",
      role: "patient",
      bloodType: "AB+",
      medicalHistory: ["Arthritis", "Gastritis"],
      allergies: ["Shellfish"],
      currentMedication: ["Ibuprofen"],
      testTaken: ["Blood Test", "X-ray"],
      appointments: [],
      reports: [],
    },
    {
      name: "David Kim",
      age: 63,
      dob: "1961-07-18",
      gender: "male",
      email: "david.kim@example.com",
      password: "patientpassword123",
      phone: "+1 555-555-6677",
      role: "patient",
      bloodType: "O-",
      medicalHistory: ["Hypertension", "Heart Disease"],
      allergies: ["Penicillin", "Aspirin"],
      currentMedication: ["Lisinopril", "Aspirin"],
      testTaken: ["Blood Test", "ECG"],
      appointments: [],
      reports: [],
    },
    {
      name: "Sophia Miller",
      age: 25,
      dob: "1999-01-09",
      gender: "female",
      email: "sophia.miller@example.com",
      password: "patientpassword123",
      phone: "+1 555-666-7788",
      role: "patient",
      bloodType: "A+",
      medicalHistory: ["Thyroid issues"],
      allergies: ["Iodine"],
      currentMedication: ["Levothyroxine"],
      testTaken: ["Blood Test"],
      appointments: [],
      reports: [],
    },
    {
      name: "Robert Brown",
      age: 29,
      dob: "1995-12-11",
      gender: "male",
      email: "robert.brown@example.com",
      password: "patientpassword123",
      phone: "+1 555-777-8899",
      role: "patient",
      bloodType: "B-",
      medicalHistory: ["Gastric Ulcer"],
      allergies: ["Milk"],
      currentMedication: ["Omeprazole"],
      testTaken: ["Blood Test", "Ultrasound"],
      appointments: [],
      reports: [],
    },
    {
      name: "Olivia White",
      age: 37,
      dob: "1987-04-03",
      gender: "female",
      email: "olivia.white@example.com",
      password: "patientpassword123",
      phone: "+1 555-888-9900",
      role: "patient",
      bloodType: "AB-",
      medicalHistory: ["PCOS", "Depression"],
      allergies: ["Peanuts"],
      currentMedication: ["Clomiphene", "Fluoxetine"],
      testTaken: ["Blood Test"],
      appointments: [],
      reports: [],
    },
    {
      name: "William Taylor",
      age: 55,
      dob: "1969-08-21",
      gender: "male",
      email: "william.taylor@example.com",
      password: "patientpassword123",
      phone: "+1 555-999-1011",
      role: "patient",
      bloodType: "O+",
      medicalHistory: ["Chronic Back Pain"],
      allergies: ["None"],
      currentMedication: ["Tramadol"],
      testTaken: ["X-ray", "MRI"],
      appointments: [],
      reports: [],
    },
    {
      name: "Ava Martinez",
      age: 31,
      dob: "1993-09-27",
      gender: "female",
      email: "ava.martinez@example.com",
      password: "patientpassword123",
      phone: "+1 555-010-1122",
      role: "patient",
      bloodType: "A-",
      medicalHistory: ["Anemia", "Migraines"],
      allergies: ["Aspirin"],
      currentMedication: ["Iron Supplements"],
      testTaken: ["Blood Test", "MRI"],
      appointments: [],
      reports: [],
    }
  ];
  
  export default patientData;
  